### ISSUE TITLE
Rearrange Button Position and Improve Page Quality.

### ISSUE THREAD

**Issue by TharVid** [TharVid/Open-Source-Badge-Generator#10]
Please place the button "Click to Download"  below the badge area and give it the name " Download Badge" and a nice UI with color. Also, exclude the "generate your badge" area from the screenshot.
Thank You!
Happy Hacking!

**Comment by TharVid** [comment]
@hhelenxu @rudhrasekar Can you please work on this? Please keep in mind your changes should not affect functionality.

**Comment by studpeps** [comment]
i would like to change the button aesthetically please assign me the same?

**Comment by Anurag-ak99** [comment]
is the issue still open, then please assign it to me.

**Comment by TharVid** [comment]
Thank you for your contributions and interests. The issue fixed now.
