### ISSUE TITLE
Semi Colon ';' after user name

### ISSUE THREAD

**Issue by h4rishabh** [TharVid/Open-Source-Badge-Generator#14]
I have noticed that there is a semicolon after user name ex: **Dear Hrishabh Kumar;**

I think it would be better if we skip ';' after userName. If you think so, then please assign this issue to me. I'll fix it.

**Comment by TharVid** [comment]
@h4rishabh I think someone already fixed that. You can open another PR to improve Badge Generator. Happy Hacking!
