### ISSUE TITLE
Changing README.md

### ISSUE THREAD

**Issue by suffisme** [TharVid/Open-Source-Badge-Generator#19]
I propose this small change in your readme for pictorial presentation in your readme.
I have changed this.
Please issue this to me and I will send PR
![image](https://user-images.githubusercontent.com/28235081/96430708-22fa1400-1220-11eb-9c85-c40c71abe6e5.png)

**Comment by TharVid** [comment]
@suffisme there was an open issue to fix UI. UI fixed now. You can send your PR again with some improvement in exiting README and I will happy to merge. Happy Hacking!
