### ISSUE TITLE
Add a share on twitter button in same style.

### ISSUE THREAD

**Issue by TharVid** [TharVid/Open-Source-Badge-Generator#33]
https://tharvid.github.io/Open-Source-Badge-Generator/
Open a share button that popup a window to share this URL https://tharvid.github.io/Open-Source-Badge-Generator/ with #proudcontributor hashtag and some cool text. Please use the same styling as the Facebook button.

**Comment by nehathakur27** [comment]
I would like to work on it.

**Comment by yhau1989** [comment]
@TharVid my changes is done
