### ISSUE TITLE
Add a download button to download div (class="container") area as an image.

### ISSUE THREAD

**Issue by TharVid** [TharVid/Open-Source-Badge-Generator#4]
Add a download button below the badge to download the badge as an image. Please add javascript code in the script file and button style code in the CSS file. html2canvas will work but other methods are highly welcomed. The badge should look the same while downloading after fetching data from Github.
Published Link- https://tharvid.github.io/Open-Source-Badge-Generator/
Good Luck!

**Comment by rudhrasekar** [comment]
Can you assign this to me ?

**Comment by TharVid** [comment]
Sure @rudhrasekar , good luck!

**Comment by TharVid** [comment]
Hey, @rudhrasekar  @hhelenxu  already added functionality to download as an image. Now just need some improvement. I am closing this issue and opening a new one for improvement.
