### ISSUE TITLE
Use Badge Generator and write update README.md

### ISSUE THREAD

**Issue by TharVid** [TharVid/Open-Source-Badge-Generator#5]
Please use https://tharvid.github.io/Open-Source-Badge-Generator/ and write instructions to use the badge generator and how it works.

**Comment by rudhrasekar** [comment]
Can you assign this to me ?

**Comment by TharVid** [comment]
I have assigned you another task. You can create a PR for this one as well.

**Comment by dishantvyas15** [comment]
Hello @TharVid !
I'd like to work on this issue.

**Comment by TharVid** [comment]
@dishantvyas15  Sure.  Good Luck!

**Comment by ghost** [comment]
Can you assign this to me ?
